name: Generate Snake

# Tetikleme zamanlaması. Bu işlem her gün saat 00:00'da çalışır.
on:
  schedule:
    - cron: "0 0 */1 * *"

# Bu komut, işlemi Actions sekmesinden otomatik olarak çalıştırmamızı sağlar.
workflow_dispatch:

# İşlemlerin sırası:
jobs:
  # Bu işlem "build" olarak adlandırılan tek bir iş içerir.
  build:
    # İşlem çalıştırılacak çalıştırıcının türünü belirtir.
    runs-on: ubuntu-latest

    # Adımlar, işlemin bir parçası olarak yürütülecek görev dizisini temsil eder.
    steps:
      # Repo'yu $GITHUB_WORKSHOP altında kontrol eder.
      - uses: actions/checkout@v2

      # Yılanı oluşturur.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ashnumpy
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Değişikliklerin durumunu gösterir.
      - run: git status

      # Değişiklikleri yapar ve ana dala iter.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: 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
          branch: master
          force: true

      # GitHub sayfalarını günceller.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          github_token: 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
          publish_dir: ./dist
          # Yapılandırmanıza bağlı olarak altındaki satırı kullanabilirsiniz.
          publish_branch: output
